#pragma once

typedef enum errorKind
{
	ARITH_EXPECTED,
	PTR_EXPECTED,
	INVALID_LVALUE,
	INTEGRAL_EXPECTED,
	MODIFIABLE_LVALUE_EX,
	UNNAMED_PARAM,
	INVALID_BRK_PLACE,
	INVALID_CNT_PLACE,
	LABELED_DECL,
	DIVISION_BY_ZERO,
	CASE_OUTSIDE_OF_SWITCH,
	DEFAULT_OUTSIDE_OF_SWITCH,
	DEFAULT_ALREADY_DECLARED,
	ARRAY_INVALID_LENGTH,
	INCOMPLETE_TYPE,
	ARRAY_MISSING_INIT,
	TOO_MANY_VALUES,
	ARITH_ONLY,
	FUNCTION_EX,
	TOO_MANY_ARGS,
	TOO_FEW_ARGS,
	COMPOSITE_EX,
	STRING_MISSING_QUOTE,
	MAX_ERRORS
}errorKind;